services:
  ai-jaf-frontend:
    build:
      target: development
    image: ai-jaf-frontend-development
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - cdp-tenant

networks:
  cdp-tenant:
    driver: bridge
